register:
    path: /api/register
    controller: App\Controller\UserController::register
    methods: POST

login:
    path: /api/login
    controller: App\Controller\UserController::login
    methods: POST

updateUser:
    path: /api/users/{id}
    controller: App\Controller\UserController::update
    methods: PUT

deleteUser:
    path: /api/users/{id}
    controller: App\Controller\UserController::delete
    methods: DELETE

createVideo:
    path: /api/videos
    controller: App\Controller\VideoController::create
    methods: POST

#Ruta para mostrar los vídeos de un usuario#
userVideos:
    path: /api/users/{id}/videos
    controller: App\Controller\VideoController::getUserVideos
    methods: GET

videoDetails:
    path: /api/videos/{id}
    controller: App\Controller\VideoController::getVideoDetails
    methods: GET

updateVideo:
    path: /api/videos/{id}
    controller: App\Controller\VideoController::update
    methods: PUT

deleteVideo:
    path: /api/videos/{id}
    controller: App\Controller\VideoController::delete
    methods: DELETE