#Ponemos un alias para hacer referencia a este stage
FROM php:8.0-fpm-alpine as build
#Actualizamos los paquetes de apk, instalamos bash y las extensiones de PHP
RUN apk --no-cache update && apk --no-cache add bash && docker-php-ext-install pdo pdo_mysql
#Descargamos Composer y copiamos su directorio en el mismo directorio del contenedor
COPY --from=composer /usr/bin/composer /usr/bin/composer
#Creamos un directorio y nos movemos a él
WORKDIR /Youfavs
#Copiamos el backend al directorio del contenedor
COPY ../ ./
#Instalamos las dependencias
RUN composer install

FROM nginx:stable-alpine
#Copiamos el directorio del anterior stage al directorio de este stage
COPY --from=build /Youfavs /var/www/Youfavs
COPY ./nginx/youfavs.com /etc/nginx/conf.d/default.conf
